# Generated by Django 5.1.7 on 2025-03-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_evinfo_car_gear_evinfo_car_running_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evinfo',
            name='cap_bars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evinfo',
            name='chg_bars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evinfo',
            name='full_chg_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evinfo',
            name='gids',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evinfo',
            name='gids_relative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evinfo',
            name='limit_chg_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evinfo',
            name='max_gids_relative',
            field=models.IntegerField(default=0),
        ),
    ]
