# Generated by Django 5.1.7 on 2025-03-28 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_evinfo_cap_bars_evinfo_chg_bars_evinfo_full_chg_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evinfo',
            name='chg_bars',
        ),
    ]
