# Generated by Django 5.1.7 on 2025-03-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_remove_evinfo_chg_bars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='command_type',
            field=models.IntegerField(choices=[(0, 'No command'), (1, 'Refresh data'), (2, 'Charge start'), (3, 'A/C on'), (4, 'A/C off'), (5, 'Read configuration')], default=0),
        ),
    ]
