# Generated by Django 5.1.7 on 2025-03-29 14:07

import db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_user_email_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tcu_pass_hash',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, validators=[db.models.CARWINGSPasswordValidator()]),
        ),
    ]
