# Generated by Django 5.1.7 on 2025-03-29 14:08

import db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_alter_user_tcu_pass_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 16 characters or fewer. Letters, digits and /./-/_ only.', max_length=16, unique=True, validators=[db.models.CARWINGSUsernameValidator()], verbose_name='username'),
        ),
    ]
