# Generated by Django 5.1.7 on 2025-03-29 14:11

import db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tcu_pass_hash',
            field=models.CharField(default='a', max_length=16, validators=[db.models.CARWINGSPasswordValidator()]),
            preserve_default=False,
        ),
    ]
