# Generated by Django 5.1.7 on 2025-04-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_car_disable_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='evinfo',
            name='soc_display',
            field=models.IntegerField(default=0),
        ),
    ]
