# Generated by Django 5.1.7 on 2025-04-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_evinfo_soc_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='periodic_refresh',
            field=models.IntegerField(choices=[(0, 'Never'), (30, 'Every 30 minutes'), (45, 'Every 45 minutes'), (60, 'Every hour'), (180, 'Every three hours'), (720, 'Every 12 hours'), (1440, 'Every day')], default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='periodic_refresh_running',
            field=models.IntegerField(choices=[(0, 'Never'), (5, 'Every 5 minutes'), (15, 'Every 15 minutes'), (30, 'Every 30 minutes'), (45, 'Every 45 minutes'), (60, 'Every hour'), (180, 'Every three hours'), (720, 'Every 12 hours'), (1440, 'Every day')], default=0),
        ),
    ]
