# Generated by Django 5.1.7 on 2025-04-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_car_periodic_refresh_car_periodic_refresh_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='evinfo',
            name='param21',
            field=models.IntegerField(default=0),
        ),
    ]
