# Generated by Django 5.1.7 on 2025-04-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_evinfo_param21'),
    ]

    operations = [
        migrations.AddField(
            model_name='evinfo',
            name='quick_charging',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alerthistory',
            name='type',
            field=models.IntegerField(choices=[(1, 'Charge stop'), (2, 'Charge start'), (3, 'Charge cable reminder'), (4, 'A/C on'), (5, 'A/C off'), (6, 'Configuration read'), (7, 'A/C auto off'), (8, 'Quick charge stop'), (96, 'Charge error'), (97, 'A/C error'), (98, 'Command timeout'), (99, 'Error')]),
        ),
    ]
