# Generated by Django 5.1.7 on 2025-04-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_evinfo_quick_charging_alter_alerthistory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='evinfo',
            name='charge_finish',
            field=models.BooleanField(default=False),
        ),
    ]
