# Generated by Django 5.1.7 on 2025-04-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_alter_evinfo_soc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evinfo',
            old_name='gids_relative',
            new_name='counter',
        ),
        migrations.RenameField(
            model_name='evinfo',
            old_name='max_gids_relative',
            new_name='max_gids',
        ),
        migrations.AlterField(
            model_name='evinfo',
            name='soc_display',
            field=models.FloatField(default=0),
        ),
    ]
