# Generated by Django 5.1.7 on 2025-04-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_rename_gids_relative_evinfo_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evinfo',
            name='kwh_content',
            field=models.FloatField(default=0),
        ),
    ]
