# Generated by Django 5.1.7 on 2025-04-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_evinfo_kwh_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='evinfo',
            name='force_soc_display',
            field=models.BooleanField(default=False),
        ),
    ]
