# Generated by Django 5.1.7 on 2025-04-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_evinfo_force_soc_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='evinfo',
            name='obc_6kw',
            field=models.IntegerField(default=0),
        ),
    ]
