# Generated by Django 5.1.7 on 2025-04-28 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_evinfo_obc_6kw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evinfo',
            old_name='kwh_content',
            new_name='wh_content',
        ),
    ]
