# Generated by Django 5.1.7 on 2025-04-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_rename_kwh_content_evinfo_wh_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('leaf_coulisred', 'LEAF Coulis Red'), ('leaf_deepblue', 'LEAF Deep Blue'), ('leaf_forgedbronze', 'LEAF Forged Bronze'), ('leaf_gunmetallic', 'LEAF Gun Metallic'), ('leaf_pearlwhite', 'LEAF Pearl White'), ('leaf_planetblue', 'LEAF Planet Blue'), ('leaf_superblack', 'LEAF Super Black'), ('env200_white', 'e-NV200 White')], default=('leaf_coulisred', 'LEAF Coulis Red'), max_length=32),
        ),
    ]
