# Generated by Django 5.1.7 on 2025-04-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_rename_kwh_content_evinfo_wh_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('l_coulisred', 'LEAF Coulis Red'), ('l_deepblue', 'LEAF Deep Blue'), ('l_forgedbronze', 'LEAF Forged Bronze'), ('l_gunmetallic', 'LEAF Gun Metallic'), ('l_pearlwhite', 'LEAF Pearl White'), ('l_planetblue', 'LEAF Planet Blue'), ('l_superblack', 'LEAF Super Black'), ('env200_white', 'e-NV200 White')], default=('l_coulisred', 'LEAF Coulis Red'), max_length=20),
        ),
    ]
