# Generated by Django 5.1.7 on 2025-08-23 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0023_car_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendToCarLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=10, max_digits=20)),
                ('lon', models.DecimalField(decimal_places=10, max_digits=20)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='disable_auth',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='send_to_car_location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.sendtocarlocation'),
        ),
    ]
