# Generated by Django 5.1.7 on 2025-09-05 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_alter_crmexcessiveairconrecord_consumption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('start_name', models.CharField(max_length=30)),
                ('start_lat', models.DecimalField(decimal_places=10, max_digits=20)),
                ('start_lon', models.DecimalField(decimal_places=10, max_digits=20)),
                ('finish_name', models.CharField(max_length=30)),
                ('finish_lat', models.DecimalField(decimal_places=10, max_digits=20)),
                ('finish_lon', models.DecimalField(decimal_places=10, max_digits=20)),
                ('point1_name', models.CharField(blank=True, max_length=30, null=True)),
                ('point1_lat', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('point1_lon', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('point2_name', models.CharField(blank=True, max_length=30, null=True)),
                ('point2_lat', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('point2_lon', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('point3_name', models.CharField(blank=True, max_length=30, null=True)),
                ('point3_lat', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('point3_lon', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('point4_name', models.CharField(blank=True, max_length=30, null=True)),
                ('point4_lat', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('point4_lon', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('point5_name', models.CharField(blank=True, max_length=30, null=True)),
                ('point5_lat', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('point5_lon', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sendtocarlocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 5, 19, 13, 37, 132846, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='car',
            name='send_to_car_location',
        ),
        migrations.AddField(
            model_name='car',
            name='route_plans',
            field=models.ManyToManyField(to='db.routeplan'),
        ),
        migrations.AddField(
            model_name='car',
            name='send_to_car_location',
            field=models.ManyToManyField(to='db.sendtocarlocation'),
        ),
    ]
