# Generated by Django 5.1.7 on 2025-09-05 19:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0028_routeplan_sendtocarlocation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
