# Generated by Django 5.1.7 on 2025-09-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0029_routeplan_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='units_imperial',
            field=models.BooleanField(default=False),
        ),
    ]
