# Generated by Django 5.1.7 on 2025-09-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0030_user_units_imperial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='carrier',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='map_version',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='navi_version',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='odometer',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='car',
            name='signal_level',
            field=models.IntegerField(default=-1),
        ),
    ]
