# Generated by Django 5.1.7 on 2025-09-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0031_car_carrier_car_map_version_car_navi_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='tcu_version',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='map_version',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='navi_version',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
