# Generated by Django 5.1.7 on 2025-09-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0032_car_tcu_version_alter_car_map_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='favorite_channels',
            field=models.JSONField(default=dict),
        ),
    ]
