# Generated by Django 5.1.7 on 2025-09-21 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0033_car_favorite_channels'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOTFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_ts', models.DateTimeField(blank=True, default=None, null=True)),
                ('upload_ts', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='probe/dotfiles/%Y/%m/%d/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.car')),
            ],
        ),
    ]
