# Generated by Django 5.1.7 on 2025-09-22 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0034_dotfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='periodic_refresh_running',
            field=models.IntegerField(choices=[(0, 'Never'), (5, 'Every 5 minutes'), (10, 'Every 10 minutes'), (15, 'Every 15 minutes'), (30, 'Every 30 minutes'), (45, 'Every 45 minutes'), (60, 'Every hour'), (180, 'Every three hours'), (720, 'Every 12 hours'), (1440, 'Every day')], default=0),
        ),
        migrations.CreateModel(
            name='CRMDistanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('consumed_wh', models.IntegerField(default=0)),
                ('regenerated_wh', models.IntegerField(default=0)),
                ('latitude', models.DecimalField(decimal_places=15, default=0, max_digits=32)),
                ('longitude', models.DecimalField(decimal_places=15, default=0, max_digits=32)),
                ('road_type', models.IntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.car')),
            ],
        ),
    ]
