# Generated by Django 5.1.7 on 2025-09-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0035_alter_car_periodic_refresh_running_crmdistancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='custom_channels',
            field=models.JSONField(default=dict),
        ),
    ]
