# Generated by Django 5.1.7 on 2025-10-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0037_alter_alerthistory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='evinfo',
            name='batt_heater_avail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evinfo',
            name='batt_heater_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evinfo',
            name='obc_6kw_avail',
            field=models.BooleanField(default=False),
        ),
    ]
