# Generated by Django 5.1.7 on 2025-10-10 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0038_evinfo_batt_heater_avail_evinfo_batt_heater_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.IntegerField(default=-1)),
                ('pending_change', models.BooleanField(default=False)),
                ('change_result', models.IntegerField(choices=[(-1, 'No command'), (0, 'Pending'), (1, 'Success'), (2, 'Failure'), (3, 'Rejected')], default=-1)),
                ('new_config_id', models.IntegerField(default=-1)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.car')),
            ],
        ),
    ]
