# Generated by Django 5.1.7 on 2025-10-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0039_probeconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandTimerSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
                ('timer_type', models.IntegerField(choices=[(0, 'One-time'), (1, 'Repeating')], default=0)),
                ('command_type', models.IntegerField(choices=[(0, 'No command'), (1, 'Refresh data'), (2, 'Charge start'), (3, 'A/C on'), (4, 'A/C off'), (5, 'Read configuration')], default=0)),
                ('last_command_result', models.IntegerField(choices=[(-1, 'Waiting'), (0, 'Success'), (1, 'Error'), (2, 'Timeout'), (3, 'Await response')], default=-1)),
                ('last_command_execution', models.DateTimeField(blank=True, default=None, null=True)),
                ('weekday_mon', models.BooleanField(default=False)),
                ('weekday_tue', models.BooleanField(default=False)),
                ('weekday_wed', models.BooleanField(default=False)),
                ('weekday_thu', models.BooleanField(default=False)),
                ('weekday_fri', models.BooleanField(default=False)),
                ('weekday_sat', models.BooleanField(default=False)),
                ('weekday_sun', models.BooleanField(default=False)),
                ('time', models.TimeField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='timer_commands',
            field=models.ManyToManyField(to='db.commandtimersetting'),
        ),
    ]
