# Generated by Django 5.1.7 on 2025-10-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0040_commandtimersetting_car_timer_commands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmabshistoryrecord',
            name='direction',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='crmabshistoryrecord',
            name='vehicle_speed_end',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='crmabshistoryrecord',
            name='vehicle_speed_start',
            field=models.FloatField(default=0),
        ),
    ]
