# Generated by Django 5.1.7 on 2025-10-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0041_alter_crmabshistoryrecord_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', max_length=32),
        ),
    ]
