# Generated by Django 5.1.7 on 2025-10-29 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0042_user_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerthistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
