# Generated by Django 5.1.7 on 2026-07-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0044_alter_dotfile_upload_ts_alter_routeplan_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='route_plans',
            field=models.ManyToManyField(blank=True, to='db.routeplan'),
        ),
        migrations.AlterField(
            model_name='car',
            name='send_to_car_location',
            field=models.ManyToManyField(blank=True, to='db.sendtocarlocation'),
        ),
        migrations.AlterField(
            model_name='car',
            name='timer_commands',
            field=models.ManyToManyField(blank=True, to='db.commandtimersetting'),
        ),
    ]
