# Generated by Django 5.1.7 on 2026-07-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0045_alter_car_route_plans_alter_car_send_to_car_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='hmac_key',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='tcu_type',
            field=models.CharField(choices=[('continental2012', 'Continental 2012-2015'), ('ficosa2016', 'Ficosa 2016-2019')], default='continental2012', max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='command_type',
            field=models.IntegerField(choices=[(0, 'No command'), (1, 'Refresh data'), (2, 'Charge start'), (6, 'Charge start 80%'), (3, 'A/C on'), (4, 'A/C off'), (5, 'Read configuration'), (7, 'Door unlock'), (8, 'Door lock'), (9, 'Horn & light'), (10, 'Stop Horn & light')], default=0),
        ),
        migrations.AlterField(
            model_name='commandtimersetting',
            name='command_type',
            field=models.IntegerField(choices=[(0, 'No command'), (1, 'Refresh data'), (2, 'Charge start'), (6, 'Charge start 80%'), (3, 'A/C on'), (4, 'A/C off'), (5, 'Read configuration'), (7, 'Door unlock'), (8, 'Door lock'), (9, 'Horn & light'), (10, 'Stop Horn & light')], default=0),
        ),
    ]
