# Generated by Django 5.1.7 on 2026-07-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0046_car_hmac_key_car_tcu_type_alter_car_command_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.TextField(choices=[('l_coulisred', 'LEAF Coulis Red'), ('l_deepblue', 'LEAF Deep Blue'), ('l_forgedbronze', 'LEAF Forged Bronze'), ('l_gunmetallic', 'LEAF Gun Metallic'), ('l_pearlwhite', 'LEAF Pearl White'), ('l2_pearlwhite', 'LEAF ZE1 Pearl White'), ('l_planetblue', 'LEAF Planet Blue'), ('l_superblack', 'LEAF Super Black'), ('env200_white', 'e-NV200 White')], default='l_planetblue'),
        ),
    ]
