# Generated by Django 5.1.7 on 2026-07-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0047_alter_car_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerthistory',
            name='type',
            field=models.IntegerField(choices=[(1, 'Charge stop'), (2, 'Charge start'), (3, 'Charge cable reminder'), (4, 'A/C on'), (5, 'A/C off'), (6, 'Configuration read'), (7, 'A/C auto off'), (8, 'Quick charge stop'), (9, 'Battery heater start'), (10, 'Battery heater stop'), (11, 'Charge start 80%'), (96, 'Charge error'), (97, 'A/C error'), (98, 'Command timeout'), (99, 'Error')]),
        ),
    ]
