# Generated by Django 5.1.7 on 2026-07-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0048_alter_alerthistory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='hmac_key',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
