# Generated by Django 5.1.7 on 2026-07-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0051_alter_alerthistory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='command_type',
            field=models.IntegerField(choices=[(0, 'No command'), (1, 'Refresh data'), (2, 'Charge start'), (6, 'Charge start 80%'), (3, 'A/C on'), (4, 'A/C off'), (5, 'Read configuration'), (7, 'Door unlock'), (8, 'Door lock'), (9, 'Horn'), (10, 'Lights'), (11, 'Horn & Lights'), (12, 'Stop Horn & light')], default=0),
        ),
        migrations.AlterField(
            model_name='commandtimersetting',
            name='command_type',
            field=models.IntegerField(choices=[(0, 'No command'), (1, 'Refresh data'), (2, 'Charge start'), (6, 'Charge start 80%'), (3, 'A/C on'), (4, 'A/C off'), (5, 'Read configuration'), (7, 'Door unlock'), (8, 'Door lock'), (9, 'Horn'), (10, 'Lights'), (11, 'Horn & Lights'), (12, 'Stop Horn & light')], default=0),
        ),
    ]
