# Generated by Django 5.1.7 on 2026-07-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0053_alter_alerthistory_type_alter_car_command_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.TextField(choices=[('l_coulisred', 'LEAF Coulis Red'), ('l_deepblue', 'LEAF Deep Blue'), ('l_forgedbronze', 'LEAF Forged Bronze'), ('l_gunmetallic', 'LEAF Gun Metallic'), ('l_pearlwhite', 'LEAF Pearl White'), ('l2_pearlwhite', 'LEAF ZE1 Pearl White'), ('l2_gunmetallic', 'LEAF ZE1 Gun Metallic'), ('l2_jadefrostmetallic', 'LEAF ZE1 Jade Frost Metallic'), ('l2_superblack', 'LEAF ZE1 Super Black'), ('l2_vividblue', 'LEAF ZE1 Vidid Blue'), ('l_planetblue', 'LEAF Planet Blue'), ('l_superblack', 'LEAF Super Black'), ('env200_white', 'e-NV200 White')], default='l_planetblue'),
        ),
    ]
