# Generated by Django 5.1.7 on 2026-08-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0054_alter_car_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='evinfo',
            name='cabin_temp',
            field=models.FloatField(default=0),
        ),
    ]
