# Generated by Django 5.1.7 on 2026-08-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0058_alter_alerthistory_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleHealthInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtc_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('dtc_short', models.JSONField(default=None, null=True)),
                ('dtc_long', models.JSONField(default=None, null=True)),
                ('tpms_light', models.BooleanField(default=False)),
                ('tpms_fr', models.IntegerField(default=0)),
                ('tpms_fl', models.IntegerField(default=0)),
                ('tpms_rr', models.IntegerField(default=0)),
                ('tpms_rl', models.IntegerField(default=0)),
                ('maintenance_alert', models.BooleanField(default=False)),
                ('mileage', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
