# Generated by Django 5.1.7 on 2026-08-16 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0059_vehiclehealthinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='veh_health',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.vehiclehealthinfo'),
        ),
    ]
