# Generated by Django 5.1.7 on 2026-08-16 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0060_car_veh_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='veh_health',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.vehiclehealthinfo'),
        ),
    ]
