# Generated by Django 5.1.7 on 2026-08-16 12:01

import db.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0061_alter_car_veh_health'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_created', models.DateTimeField(auto_now_add=True)),
                ('expiration_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('transfer_code', models.CharField(default=db.models.generate_transfer_code, max_length=32)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.car')),
            ],
        ),
    ]
