# Generated by Django 6.1 on 2026-08-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0062_cartransferrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_key',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_recovery',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
