# Generated by Django 6.1 on 2026-08-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0063_user_otp_key_user_otp_recovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cmd_pin_hash',
            field=models.TextField(blank=True, default=None, null=True),
        )
    ]
