# Generated by Django 6.1 on 2026-09-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0068_alter_alerthistory_type_alter_car_command_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evinfo',
            name='power_available',
            field=models.BooleanField(default=False),
        ),
    ]
