# Generated by Django 6.1 on 2026-09-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0069_evinfo_power_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='evinfo',
            name='charging_interrupted',
            field=models.BooleanField(default=False),
        ),
    ]
