# Generated by Django 6.1 on 2026-09-26 14:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0070_evinfo_charging_interrupted'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmtroublerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
