version: "2.1"

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      PSQL_DATABASE: ${PSQL_NAME}
      PSQL_USER: ${PSQL_USERNAME}
      PSQL_PASSWORD: ${PSQL_PASSWORD}
      PSQL_DATABASE_HOST: db
      PSQL_DATABASE_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      WORKER_CONNECTIONS: ${WORKER_CONNECTIONS}
      WORKER_TIMEOUT: ${WORKER_TIMEOUT}
      WORKERS: ${WORKERS}
      TZ: ${TZ}
    restart: always
    volumes:
      - ./carwings/:/app/carwings/
      - ./staticfiles/:/app/staticfiles/
      - ./logs/:/app/logs/
    ports:
      - "${BACKEND_PORT}:80"
      - "${TCPSERVER_PORT}:55230"
  db:
    image: postgres:14
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${PSQL_NAME}
      POSTGRES_USER: ${PSQL_USERNAME}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
    volumes:
      - psql_data:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:7


volumes:
  psql_data: