# Generated by Django 5.1.7 on 2025-04-29 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=500, unique=True)),
                ('device_type', models.CharField(blank=True, max_length=100)),
                ('device_os', models.CharField(blank=True, max_length=100)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('push_notification_key', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_metadata', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'token_metadata',
            },
        ),
    ]
