# Generated by Django 5.1.7 on 2025-05-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenmetadata',
            name='lang',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
