import decimal
from typing import Dict, Any, Tuple

from tculink.gdc_proto import WH_PER_GID_GEN1
from tculink.gdc_proto.acp245 import parser


def parse_auth_ev_pload(acp_encoded_data: bytes) -> Tuple[dict, int]:
    result: Dict[str, Any] = {}
    offset = 0

    app_header, consumed = parser.decode_app_header(acp_encoded_data, offset)
    result["app_header"] = app_header
    offset += consumed

    version, consumed = parser.parse_version_ficosa(acp_encoded_data, offset)
    result["version"] = version
    offset += consumed

    veh_desc, consumed = parser.decode_veh_desc(acp_encoded_data, offset)
    result["veh_desc"] = veh_desc
    offset += consumed

    # Dest ID = specific function / program in TCU
    dest_id = parser.get_single_byte(acp_encoded_data, offset)
    result["dest_id"] = dest_id
    offset += 1

    # Random request identifier generated by server, "session token" of sorts
    source_id = parser.get_single_byte(acp_encoded_data, offset)
    offset += 1
    result["source_id"] = source_id

    timestamp, consumed = parser.decode_timestamp(acp_encoded_data, offset)
    result["timestamp"] = timestamp
    offset += consumed

    auth, consumed = parser.decode_acp_auth(acp_encoded_data, offset)
    offset += consumed
    result["auth"] = auth

    gps, consumed = parser.decode_gps_position(acp_encoded_data, offset)
    offset += consumed
    result["position"] = gps

    return result, offset

def parse_ev_request(acp_encoded_data: bytes) -> Tuple[dict, int]:
    result: Dict[str, Any] = {}
    offset = 0

    app_header, consumed = parser.decode_app_header(acp_encoded_data, offset)
    result["app_header"] = app_header
    offset += consumed

    veh_desc, consumed = parser.decode_veh_desc(acp_encoded_data, offset)
    result["veh_desc"] = veh_desc
    offset += consumed

    # Dest ID = specific function / program in TCU
    dest_id = parser.get_single_byte(acp_encoded_data, offset)
    result["dest_id"] = dest_id
    offset += 1

    # Random request identifier generated by server, "session token" of sorts
    source_id = parser.get_single_byte(acp_encoded_data, offset)
    offset += 1
    result["source_id"] = source_id

    timestamp, consumed = parser.decode_timestamp(acp_encoded_data, offset)
    result["timestamp"] = timestamp
    offset += consumed

    gps, consumed = parser.decode_gps_position(acp_encoded_data, offset)
    offset += consumed
    result["position"] = gps

    auth, consumed = parser.decode_acp_auth(acp_encoded_data, offset)
    offset += consumed
    result["auth"] = auth

    return result, offset

def parse_probe_request(acp_encoded_data: bytes) -> Tuple[dict, int]:
    result: Dict[str, Any] = {}
    offset = 0

    app_header, consumed = parser.decode_app_header(acp_encoded_data, offset)
    result["app_header"] = app_header
    offset += consumed

    veh_desc, consumed = parser.decode_veh_desc(acp_encoded_data, offset)
    result["veh_desc"] = veh_desc
    offset += consumed

    # Dest ID = specific function / program in TCU
    dest_id = parser.get_single_byte(acp_encoded_data, offset)
    result["dest_id"] = dest_id
    offset += 1

    # Random request identifier generated by server, "session token" of sorts
    source_id = parser.get_single_byte(acp_encoded_data, offset)
    offset += 1
    result["source_id"] = source_id

    timestamp, consumed = parser.decode_timestamp(acp_encoded_data, offset)
    result["timestamp"] = timestamp
    offset += consumed

    gps, consumed = parser.decode_gps_position(acp_encoded_data, offset)
    offset += consumed
    result["position"] = gps

    auth, consumed = parser.decode_acp_auth(acp_encoded_data, offset)
    offset += consumed
    result["auth"] = auth

    return result, offset


def parse_ev_info(data: bytes, offset: int) -> Tuple[dict, int]:
    d, all_li = parser._decode_ie_element(data, offset, 0, parser.IE_Element(length=0x17))
    d = d["value"]
    # Format Doc: EVInfo.ods @ nissan-leaf-tcu repo

    pluggedin = (d[0] & 0b00001001) == 9
    charging = ((d[0] & 0b01000000) >> 6) == 1
    ignition = ((d[0] & 0b00100000) >> 5) == 1
    # TODO quickcharge
    quick_charging = False
    finish_flag = (d[0] & 0b10000000) > 0
    acstate = ((d[0] & 0b00000010) >> 1) == 1

    chargebars = 0
    chgbar_multiplier = (d[9] & 0b11111000) >> 3
    if chgbar_multiplier < 0x1F:
        chargebars = (((d[9] & 0b00000111) << 3) | ((d[10] & 0b11100000) >> 5)) / chgbar_multiplier

    drive_status = (d[4] & 0b11111000) >> 3

    soh = ((d[6] & 0b00111111) << 1) | ((d[7] & 0b10000000) >> 7)

    soc = (((d[7] & 0b01111111) << 3) | ((d[8] & 0b11100000) >> 3))/10.0
    soc_display_int = d[11]
    soc_display = ((d[17] << 4) | ((d[18] & 0b11110000) >> 4))
    if soc_display == 0:
        soc_display = soc_display_int
    else:
        soc_display = soc_display / 8.00

    gids = (d[5] << 2) | ((d[6] & 0b11000000) >> 6)

    acon = (d[19] << 2) | ((d[20] & 0b11000000) >> 6)
    acoff = ((d[21] & 0b00111111) << 4) | ((d[22] & 0b11110000) >> 4)

    # not sure if this is cap bars, zero out if its OOB
    capacity_bars = (d[13] & 0b11110000) >> 4
    if capacity_bars > 12:
        capacity_bars = 0



    range_acon = int(decimal.Decimal(
        (acon*((gids*WH_PER_GID_GEN1)/10000))).__round__(0))
    range_acoff = int(decimal.Decimal(
        (acoff*((gids*WH_PER_GID_GEN1)/10000))).__round__(0))

    chg_time_1 = ((d[2] & 0b00011111) << 6) | ((d[3] & 0b11111100) >> 2)
    chg_time_2 = (d[1] << 3) | ((d[2] & 0b11100000) >> 5)
    chg_time_3 = (d[14] << 3) | ((d[15] & 0b11100000) >> 5)

    if finish_flag:
        charging = False
        quick_charging = False

    return {
        "acon": range_acon,
        "acoff": range_acoff,
        "pluggedin":pluggedin,
        "charging": charging,
        "quick_charging": quick_charging,
        "finish_flag": finish_flag,
        "acstate": acstate,
        "chargebars": chargebars,
        "ignition": ignition,
        "parked": drive_status == 1,
        "direction_forward": drive_status == 4,
        "soc": soc,
        "soc_display": soc_display,
        "gids": gids,
        "soh": soh,
        "obc_6kw_exist": False,
        "batt_heat_exist": False,
        "batt_heat_active": False,
        "capacity_bars": capacity_bars,
        "1kw_chg": chg_time_1,
        "3kw_chg": chg_time_2,
        "6kw_chg": chg_time_3
    }, all_li